output "eks_cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "eks_cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "eks_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "eks_cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.name
}

output "consul_public_endpoint_url" {
  description = "HCP Consul Public URL"
  value       = hcp_consul_cluster.this.consul_public_endpoint_url
}

output "consul_bootstrap_token" {
  description = "HCP Consul Token"
  value       = hcp_consul_cluster.this.consul_root_token_secret_id
  sensitive   = true
}

output "ecs_ingress_address" {
  value = "http://${aws_lb.hashicups.dns_name}"
}

output "eks_ingress_address" {
  value = module.demo_app.hashicups_url
}
